logstash:
  image: logstash
  volumes:
    - ./conf/:/config-dir/
#    - ./data/qa-proxy/:/logs/
    - ./patterns/:/opt/logstash/patterns/
  ports:
    - 5044:5044
    - 5044:5044/udp
  environment:
    LOGSPOUT: ignore
  links:
    - elasticsearch
    - redis
  command:  logstash -f /config-dir/*.conf
elasticsearch:
  image: elasticsearch
  ports:
    - 9200:9200
  environment:
    LOGSPOUT: ignore
kibana:
  image: kibana
  links:
    - elasticsearch
  ports:
    - 5601:5601
  environment:
    LOGSPOUT: "ignore"
redis:
  image: redis
  ports:
    - 6379:6379
# logspout:
#   image: rtoma/logspout-redis-logstash
#   command: 'redis://redis'
#   environment:
#     - DEBUG=true
#     - REDIS_KEY=logstash
#     - REDIS_DOCKER_HOST=$HOSTNAME
#     - REDIS_LOGSTASH_TYPE=docker
#     - LOGSPOUT=ignore
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#   links:
#     - redis
# filebeat:
#   image: prima/filebeat
#   links:
#     - logstash
#   volumes:
#     - ./filebeat/filebeat-apache.yml:/etc/filebeat/filebeat.yml
# #    - /c/Users/grund/tmp/:/var/log/apache2/
